### ISSUE TITLE
Подумать над возможностью передачи кастомного кода в конструктор

### ISSUE THREAD

**Issue by Skyuzii** [Skyuzii/HarabaSourceGenerators#2]

**Comment by Skyuzii** [comment]
В голову приходят два варианта:

1. Можно передавать в атрибут флаг. Если есть такой флаг, то при компиляции будет ворнинг, который требует в этом классе создать метод, в котором и идёт кастомный код. Если флага нет, то соответственно, ничего не требует
2. Возможность передать в атрибут Action, который выполняется в конце конструктора

**Comment by onyxmaster** [comment]
А [partial method](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods#partial-methods) не поможет?

**Comment by Skyuzii** [comment]
Поможет. Отличный вариант. Спасибо!

**Comment by Skyuzii** [comment]
> В голову приходят два варианта:
> 
> 1. Можно передавать в атрибут флаг. Если есть такой флаг, то при компиляции будет ворнинг, который требует в этом классе создать метод, в котором и идёт кастомный код. Если флага нет, то соответственно, ничего не требует
> 2. Возможность передать в атрибут Action, который выполняется в конце конструктора

3. Возможность пометить метод атрибутом типа InjectInitialize (над названием подумать). Метод с таким атрибутом будет вызываться в конце конструктора
4. Использование partial метода
