### ISSUE TITLE
не генерирует конструктор если указать [Inject] только для класса

### ISSUE THREAD

**Issue by SergeyHoroshun** [Skyuzii/HarabaSourceGenerators#3]
похоже, ошибка там где определяется порядок параметров

var orderedFields = fields.OrderBy(x => x.GetAttributes()
                                                     .First(e => e.AttributeClass.Name == nameof(InjectAttribute))
                                                     .ConstructorArguments.FirstOrDefault().Value ?? default(int)).ToList();

**Comment by Skyuzii** [comment]
Спасибо, что сообщили. Пофиксил
